### ISSUE TITLE
Activation Issue

### ISSUE THREAD

**Issue by alteadev** [cowai/camerarawpreviews#14]
In order to be able to activate the App, you should rename the App folder "CameraRawPreviews" inside the NextCloud Apps folder.

To activate: `sudo -u www-data php occ app:enable CameraRawPreviews`

**Comment by stratege1401** [comment]
what command ??

-u ???

**Comment by stratege1401** [comment]
ok, it's late, i am tired ... almost kill the serveur... getting a seg fault and php-fpm crashing 

serveur error 503 when accessing my nextcloud

removing /etc/php/7.0/cli/conf.d/20-imagick.ini

control regain, server ok.

going to sleep.

**Comment by cowai** [comment]
@stratege1401 Hello,
when you have put the camerarawpreviews folder inside your apps folder, instead of activating through the gui, you should try "php occ app:enable CameraRawPreviews" as the same user as your web server.
Also some distros have problems with imagick and php7.

**Comment by stratege1401** [comment]
Hello thanks for answer...

My /var/www/html is my nextcloud root directorie ( some laziness during install on my prototype).
CameraRawPreviews folder is under /html/apps
ls -la show www-data:www-data with drwxr-xr-x
Problem, acting as root php occ app:enable CameraRawPreviews give "could not open input files off" and if doing a su www-data I can't as user not available due to nologin constraints...

My final hardware should have been delivered this Monday but is late because weather is bad in France ( 5 cm of snow near Paris and road traffic goes to hell !!!!!! ) 

So I will try again tomorrow doing a nice imagick install on Debian

**Comment by stratege1401** [comment]
Under debian 9.3, you might have trouble with some users getting message "user unavailable".
This is due to the nologing.
to bypass this use this temporary solution:
su -l www-data -s /bin/bash  ( with www-dat the users with nologin )




STILL, i am getting a nice red square with:

www-data@nextcloud:~/html$  php occ app:enable camerarawpreviews


  [Exception]
  App not found


app:enable [-g|--groups GROUPS] [--] <app-id>

**Comment by cowai** [comment]
Pull latest master.
I think potensial issues are fixed now. Make sure the app folder is lower case "camerarawpreviews".
